### ISSUE TITLE
Forward freaks out

### ISSUE THREAD

**Issue by Robo4607** [CIS4607/KOP_Bot#10]
Going forward with RT on the Logitech controller works correctly at very low speeds, shortly after it goes to what appears full speed. It then remains at the speed until LT is pressed. Cause unknown.
- [x] Investigate causes. I think it quite possible smooth motion code is somehow causing the issue.
- [X] Implement code fixes. I have made several improvements to the drivetrain code including the smooth motion portion which may fix the issue.
- [x] Test the code to confirm fix. Testing may or may not have happened with some of the fixes. I have not heard.
- [ ] Create release .1 as our driving release. Also move code to production branch.

**Comment by Penchant** [comment]
When going to a very low speed you must accelerating somewhat slow. I believe the issue may be related to an issue in the smooth motion code. Making updates now.
